# Generated by Django 5.0 on 2025-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigoBarras', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precioCompra', models.FloatField()),
                ('precioVenta', models.FloatField()),
                ('stockActual', models.FloatField()),
                ('stockMinimo', models.FloatField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
